NermoMaxVelocity-v0: &nermo-defaults
  n_timesteps: !!float 3e6
  normalize: false
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 1024 #before: 2048
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 10
  ent_coef: 0.0
  max_grad_norm: 0.5
  vf_coef: 0.5
  learning_rate: 0.0003 #before:0.0002
  use_sde: False
  sde_sample_freq: -1
  clip_range: 0.2
  env_wrapper:
    - gym.wrappers.rescale_action.RescaleAction:
        a: -1
        b: 1

NermoFixedVelocity-v0:
  <<: *nermo-defaults

NermoDirectedYawEnv-v0:
  <<: *nermo-defaults

NermoBound-v0:
  <<: *nermo-defaults

NermoDesiredTurningRadiusEnv-v0:
  <<: *nermo-defaults

NermoCommandedTurningRadiusEnv-v0:
  <<: *nermo-defaults

NermoCommandedTurningRadiusAndFixedVelocityEnv-v0:
  <<: *nermo-defaults

NermoCommandedTurningRadiusAndCommandedVelocityEnv-v0:
  <<: *nermo-defaults

NermoCommandedVelocity-v0:
  <<: *nermo-defaults
  # n_timesteps: !!float 1e7

nermo-short-episodes-v0:
  <<: *nermo-defaults

nermo-long-episodes-v0:
  <<: *nermo-defaults